import { chromium } from 'playwright';
import { readFileSync } from 'node:fs';
const token = readFileSync('./.ha_token','utf8').trim();
const [,, url, x1, y1, x2, y2] = process.argv;
const b = await chromium.launch();
const ctx = await b.newContext({ viewport:{width:500,height:1000}, deviceScaleFactor:2 });
const p = await ctx.newPage();
await p.addInitScript(()=>{ localStorage.setItem('ha_url','http://10.2.3.3:8123'); }, );
await p.addInitScript((t)=>{ localStorage.setItem('ha_token', t); }, token);
await p.goto(url,{waitUntil:'load'});
await p.waitForTimeout(9000);
await p.mouse.move(Number(x1), Number(y1));
await p.mouse.down();
await p.mouse.move(Number(x2), Number(y2), { steps: 12 });
await p.mouse.up();
await p.waitForTimeout(2500);
await p.screenshot({ path:'web_drag.png' });
await b.close();
console.log(`dragged (${x1},${y1}) -> (${x2},${y2})`);
